version: '3.5'

services:

  client-prod:
    container_name: aria-nnmta-prod
    build:
      context: ./client
      dockerfile: Dockerfile-prod
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
  
  server-prod:
    container_name: aria-server-prod
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production