apiVersion: v1
kind: Service
metadata:
  name: aria-server-backend
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: aria-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aria-server
spec:
  replicas: 1 
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: aria-server
    spec:
      containers:
      - image: gcr.io/aria-nnmta/aria-server:${CIRCLE_SHA1} 
        imagePullPolicy: Always
        name: aria-server
        env:
        - name: "JWT_SECRET"
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: jwt_secret
        - name: "DB_USER"
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: db_user
        - name: "DB_PASS"
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: db_pass 
        - name: "DB_HOST"
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: db_host 
        - name: "BRAINTREE_MERCHANT_ID"
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: braintree_merchant_id
        - name: "BRAINTREE_PUBLIC_KEY"
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: braintree_public_key
        - name: "BRAINTREE_PRIVATE_KEY"
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: braintree_private_key 
        ports:
          - containerPort: 8080
        readinessProbe:
          httpGet:
              path: /
              port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5